### PR TITLE
fix(docs): camel -> snake case in resource escape hatches

### LINKED ISSUE #2566: documentation for resources escape hatch uses wrong casing in code snippets
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

These lines need to be in `snake_case` (applies to all other examples below this one, too):
https://github.com/hashicorp/terraform-cdk/blob/8d33d56a84301ef357bae4218a020a8d93b80ce4/website/docs/cdktf/concepts/resources.mdx?plain=1#L540-L542

```
fromPort => from_port
toPort => to_port
cidrBlocks => cidr_blocks
```

### References

Similar to #2561

### PR DESCRIPTION
**Pull request by Maed223**
Closes #2566

### CODE REVIEW

File: examples/java/documentation/src/main/java/com/mycompany/app/resources/MainResources.java [hunk 1]
```diff
@@ -147,10 +147,10 @@ public MainResources(Construct scope, String id) {
...
                                 put("content", new HashMap<String, Object>() {
                                         {
-                                                put("fromPort", "${ingress.value}");
-                                                put("toPort", "${ingress.value}");
-                                                put("cidrBlocks", Arrays.asList("0.0.0.0/0"));
-                                                put("protocal", "-1");
+                                                put("from_port", "${ingress.value}");
+                                                put("to_port", "${ingress.value}");
+                                                put("cidr_blocks", Arrays.asList("0.0.0.0/0"));
+                                                put("protocol", "-1");
```
Comment (ansgarm) [inline examples/java/documentation/src/main/java/com/mycompany/app/resources/MainResources.java:153]: Good catch!

File: examples/python/documentation/resources.py [hunk 2]
```diff
@@ -125,9 +125,9 @@ def __init__(self, scope: Construct, name: str):
                 vpc_id="vpcs",
                 egress=[
                     {
-                        "fromPort": 0,
-                        "toPort": 0,
-                        "ciderBlocks": ["0.0.0.0/0"],
+                        "from_port": 0,
+                        "to_port": 0,
+                        "cider_blocks": ["0.0.0.0/0"],
```
Comment (ansgarm) [inline examples/python/documentation/resources.py:130]: Spotted another typo that was there before
```suggestion
                        "cidr_blocks": ["0.0.0.0/0"],
```

File: examples/python/documentation/resources.py [hunk 3]
```diff
@@ -136,9 +136,9 @@ def __init__(self, scope: Construct, name: str):
         sq.add_override("dynamic.ingress", {
             "for_each": ports.list_value,
             "content": {
-                "fromPort": "${ingress.value}",
-                "toPort": "${ingress.value}",
-                "ciderBlocks": ["0.0.0.0/0"],
+                "from_port": "${ingress.value}",
+                "to_port": "${ingress.value}",
+                "cider_blocks": ["0.0.0.0/0"],
```
Comment (ansgarm) [inline examples/python/documentation/resources.py:141]:
```suggestion
                "cidr_blocks": ["0.0.0.0/0"],
```

File: website/docs/cdktf/concepts/resources.mdx [hunk 4]
```diff
@@ -593,9 +593,9 @@ import imports.aws.security_group.*;
                 vpc_id="vpcs",
                 egress=[
                     {
-                        "fromPort": 0,
-                        "toPort": 0,
-                        "ciderBlocks": ["0.0.0.0/0"],
+                        "from_port": 0,
+                        "to_port": 0,
+                        "cider_blocks": ["0.0.0.0/0"],
```
Comment (ansgarm) [inline website/docs/cdktf/concepts/resources.mdx:598]: I think it's safe to fix this via a suggestion instead of re-generating them 👍
```suggestion
                        "cidr_blocks": ["0.0.0.0/0"],
```

File: website/docs/cdktf/concepts/resources.mdx [hunk 5]
```diff
@@ -604,9 +604,9 @@ import imports.aws.security_group.*;
         sq.add_override("dynamic.ingress", {
             "for_each": ports.list_value,
             "content": {
-                "fromPort": "${ingress.value}",
-                "toPort": "${ingress.value}",
-                "ciderBlocks": ["0.0.0.0/0"],
+                "from_port": "${ingress.value}",
+                "to_port": "${ingress.value}",
+                "cider_blocks": ["0.0.0.0/0"],
```
Comment (ansgarm) [inline website/docs/cdktf/concepts/resources.mdx:609]:
```suggestion
                "cidr_blocks": ["0.0.0.0/0"],
```

**Review by ansgarm — APPROVED** [review]
Approved, but spotted a separate typo that we can fix while we're at it

**Comment by ansgarm** [comment]
I just went ahead and added my suggestions myself 😄
image
