### PR TITLE
fix: iterator examples

### LINKED ISSUE #2452: "Using Iterators on Complex Types" documentation sample code does not work
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf version: 0.14.3
python version: 3.8.10
terraform modules: terraform-aws-modules/s3-bucket/aws@3.6.0

### Affected Resource(s)

When trying to use the Iterator on Complex Types in the example documented here https://developer.hashicorp.com/terraform/cdktf/concepts/iterators#using-iterators-on-complex-types,  I get an error saying that "The given "for_each" argument value is unsuitable: "for_each" supports maps and sets of strings, but you have provided a set containing type object." - see gist below for the complete error message

### Debug Output

[https://gist.github.com/cosminnicula/e32ccabed695fb646aefa2cb6e1609c8](https://gist.github.com/cosminnicula/e32ccabed695fb646aefa2cb6e1609c8)

### Expected Behavior

The code should work as expected.

### Actual Behavior

An error pops out, saying that "The given "for_each" argument value is unsuitable: "for_each" supports maps and sets of strings, but you have provided a set containing type object."

### Steps to Reproduce

Initialize a minimal CDKTF project with Python including the "Using Iterators on Complex Types" sample code, then run `cdktf apply`.

### Important Factoids

N/A

### References

N/A

### PR DESCRIPTION
**Pull request by mutahhir**
fixes #2452

Terraform only [supports a set of strings, and maps](https://developer.hashicorp.com/terraform/language/meta-arguments/for_each) with the `for_each` meta-argument.

The way for CDKTF to support complex list iterators would be to implement a kind of [for expression](https://developer.hashicorp.com/terraform/language/expressions/for) when synthesising the iterator with `for_each`, however that isn't currently supported. 

For now, this PR updates the example code to use maps instead of a complex list, until we implement the above.

### CODE REVIEW

**Review by DanielMSchmidt — CHANGES_REQUESTED** [review]
I think this should use the other iterator type

File: examples/csharp/documentation/IteratorStack.cs [hunk 1]
```diff
@@ -33,22 +36,29 @@ public IteratorStack(Construct scope, string name) : base(scope, name)
...
+                        { "name", "images" },
+                        { "tags", new Dictionary<string, string> {
+                            { "app", "image-converter" }
+                        }}
+                    }
                 }
             });
-            ListTerraformIterator listIterator = ListTerraformIterator.FromList(listLocal.AsList);
-            new S3Bucket(this, "listBucket", new S3BucketConfig {
+            ListTerraformIterator listIterator = ListTerraformIterator.FromList(complexLocal.AsAnyMap);
```
[the remark this answers is not in the document]
Comment (mutahhir) [reply examples/csharp/documentation/IteratorStack.cs]: Good catch.

File: examples/java/gradle-shared-module/gradle/wrapper/gradle-wrapper.properties [hunk 2]
```diff
@@ -1,5 +1,5 @@
-#Wed Dec 18 13:39:13 EST 2019
-distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-all.zip
+#Wed Jan 04 09:19:33 PKT 2023
```
Comment (DanielMSchmidt) [inline examples/java/gradle-shared-module/gradle/wrapper/gradle-wrapper.properties:1]: This is not related, should this even be tracked 🤔

**Review by DanielMSchmidt — APPROVED** [review]

File: examples/java/gradle-shared-module/gradle/wrapper/gradle-wrapper.properties (hunk 2 above)
Comment (mutahhir) [reply examples/java/gradle-shared-module/gradle/wrapper/gradle-wrapper.properties:1]: Yeah, I think it shouldn't be. I added it because it was already there.

**Comment by mutahhir** [comment]
This is failing on CSharp because of: https://github.com/aws/jsii/issues/3870. 

we're currently on 1.71.0, while the fix is in 1.72.0.

**Comment by DanielMSchmidt** [comment]
@mutahhir I think this would be ready for a rebase, the bug should be fixed in JSII by now :)

**Comment by DanielMSchmidt** [comment]
@mutahhir I think this needs a rebase :)
