### PR TITLE
fix(provider-generator): attributes on resources should not be undefined

### LINKED ISSUE #1200: Prebuilt AWS Typing Error on Generated Resource Properties
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
```
cdktf --version
0.7.0

"typescript": "4.4.4"
"@cdktf/provider-aws": "2.0.13"
```

### Affected Resource(s)
```
IAM.IamRole
S3.S3Bucket
```
and maybe more...

### Debug Output
https://gist.github.com/vu-bui/7001cd3001792b9d447b1874e9e5e0dc

### Expected Behavior
The properties that are specified as optional inputs and are auto-generated by terraform should not be `undefined` as they're Resolvable

### Actual Behavior
`tsc` throws compile error

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
While this is true in general also on structs we can not implement it there without removing the ability to use setters since setter and getter types need to be the same. This is a short term fix to get ridof the regression we introduced.

Closes #1200

### CODE REVIEW

File: test/typescript/providers/main.ts [hunk 1]
```diff
@@ -59,14 +59,21 @@ export class NamespacedProviders extends TerraformStack {
...
       {}
     );
+
+    const role = new Aws.iam.IamRole(this, "role", {
+      assumeRolePolicy: "assumeRolePolicy",
+    });
+    new Aws.iam.IamRolePolicyAttachment(this, "lambda-role-vpc-att", {
+      policyArn:
+        "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole",
+      role: role.name,
```
Comment (skorfmann) [inline test/typescript/providers/main.ts:69]: that's the one which changed before, right? Without these changes it would have to be `role.name!`?

Comment (DanielMSchmidt) [reply test/typescript/providers/main.ts:69]: exactly 👍

Comment (skorfmann) [reply test/typescript/providers/main.ts:69]: top 👍

**Review by skorfmann — APPROVED** [review]
:shipit:

File: packages/@cdktf/provider-generator/lib/get/generator/emitter/attributes-emitter.ts [hunk 2]
```diff
@@ -21,7 +24,12 @@ export class AttributesEmitter {
     const hasInputMethod = isStored;
 
     if (isStored) {
-      this.code.line(`private ${att.storageName}?: ${att.type.storedName}; `);
+      this.code.line(
+        `private ${att.storageName}?: ${
+          // TODO: this is a hack to make optional attributes required on resources but not on structs
+          this.context === "resource" ? att.type.name : att.type.storedName
```
Comment (jsteinich) [inline packages/@cdktf/provider-generator/lib/get/generator/emitter/attributes-emitter.ts:30]: What is the case where this check is needed? Since we are always are emitting as an optional field and the only difference between `type.name` and `type.storedName` is a possible `| undefined` it doesn't seem like it changes anything.

File: packages/@cdktf/provider-generator/lib/get/generator/models/attribute-model.ts [hunk 3]
```diff
@@ -158,20 +158,30 @@ export class AttributeModel {
...
+        _type: "put",
+        type: this.type.storedName,
+      };
+    }
+
+    // TODO: this is a hack to make optional attributes required on resources but not on structs
+    if (context === "resource") {
+      return {
+        _type: "set",
+        type: `${this.type.name}${this.isProvider ? "| undefined" : ""}`,
```
Comment (jsteinich) [inline packages/@cdktf/provider-generator/lib/get/generator/models/attribute-model.ts:177]:
```suggestion
        type: `${this.type.name}${this.isProvider ? " | undefined" : ""}`,
```

File: packages/@cdktf/provider-generator/lib/get/generator/models/attribute-model.ts [hunk 4]
```diff
@@ -158,20 +158,30 @@ export class AttributeModel {
...
+      };
+    }
+
+    return {
+      _type: "set",
+      type: `${this.type.storedName}${this.isProvider ? "| undefined" : ""}`,
```
Comment (jsteinich) [inline packages/@cdktf/provider-generator/lib/get/generator/models/attribute-model.ts:183]: I'm not sure I follow why structs should be different.

Comment (DanielMSchmidt) [reply packages/@cdktf/provider-generator/lib/get/generator/models/attribute-model.ts:183]: Because we currently support setters in structs, leading to different types for getters and setters on these. There is a bigger solution that should replace this temporary "make it the old thing in this case" extra case

File: packages/@cdktf/provider-generator/lib/get/generator/emitter/attributes-emitter.ts (hunk 2 above)
Comment (DanielMSchmidt) [reply packages/@cdktf/provider-generator/lib/get/generator/emitter/attributes-emitter.ts]: I remove this, not sure why I had it in the first place. If something arises I'll add a test to catch it 👍

File: packages/@cdktf/provider-generator/lib/get/generator/models/attribute-model.ts (hunk 4 above)
Comment (DanielMSchmidt) [reply packages/@cdktf/provider-generator/lib/get/generator/models/attribute-model.ts]: I removed this, not sure why I had it in the first place. If something arises I'll add a test to catch it 👍
