### PR TITLE
fix(provider-generator): fix resources named 'license' causing collisions with LICENSE file on case-insensitive filesystems for Go packages

### LINKED ISSUE #2627: Consul pre-built provider fails pull on case-insensitive filesystem
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

CDKTF: 0.15.4
Provider: cdktf-provider-consul-go @ 3.0.0

### Debug Output

https://gist.github.com/krarey/7c3008454c57ad806d622d3ac017f3a5

### Expected Behavior

When attempting to pull the Consul pre-built provider for CDKTF on a MacOS host, the provider fails to pull due to case-insensitivity conflicts between the `LICENSE` file and `license` directory. MacOS formats its root volume with APFS in case-insensitive mode by default, so this incompatibility would impact most developers working from MacOS.

### Actual Behavior

Provider fails to pull from github. See linked gist for raw output.

### PR DESCRIPTION
**Pull request by ansgarm**
Resolves #2627

I'm unsure whether releasing this as part of a patch is okay – it changes the `License` resource to `LicenseResource` which is a breaking change for folks that currently generate bindings for `consul`, so I'd rather merge this after our last patch release for the current version is out – what do you think?

### CODE REVIEW

**Review by DanielMSchmidt — APPROVED** [review]

File: packages/@cdktf/provider-generator/lib/get/generator/resource-parser.ts [hunk 1]
```diff
@@ -35,12 +35,18 @@ const RESERVED_KEYWORDS_FOR_NAMESPACES = [
   "await",
 ];
 
+const COLLIDING_NAMESPACE_NAMES = [
```
Comment (DanielMSchmidt) [inline packages/@cdktf/provider-generator/lib/get/generator/resource-parser.ts:38]: Is this covered in convert as well?

Comment (ansgarm) [reply packages/@cdktf/provider-generator/lib/get/generator/resource-parser.ts:38]: Yes, same reply as here: https://github.com/hashicorp/terraform-cdk/pull/2504#issuecomment-1385688815
😄
Existing follow-up for the "schema-less" convert that does not support this yet is here: https://github.com/hashicorp/terraform-cdk/issues/2508

Comment (DanielMSchmidt) [reply packages/@cdktf/provider-generator/lib/get/generator/resource-parser.ts:38]: Good good, I just wanted to be sure

**Comment by ansgarm** [comment]
Removed the blocking label as we already have breaking changes on `main`
