### PR TITLE
Windows Python fixes

### LINKED ISSUE #194: Windows Javascript error when running `cdktf init --template="python"`
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Expected Behavior

No error.
### Actual Behavior

Experienced this error when using the CLI to init my Python project.
### Steps to Reproduce

Run `cdftf init --template="python"`
### References

image

* #0000

### PR DESCRIPTION
**Pull request by jsteinich**
Aiming to fix #194 , #267, #268 and anything else that comes up while getting python working on Windows.

### CODE REVIEW

**Comment by jsteinich** [comment]
I'm making progress but I think I'm getting blocked by something related to #262.
Following the python getting started, I'm getting `ImportError: cannot import name 'Instance' from 'imports.aws' (unknown location)`

File: packages/cdktf-cli/templates/python/Pipfile [hunk 1]
```diff
@@ -4,4 +4,4 @@ url = "https://pypi.org/simple"
 verify_ssl = true
 
 [requires]
-python_version = "3.7"
\ No newline at end of file
+python_version = "3"
```
Comment (skorfmann) [inline packages/cdktf-cli/templates/python/Pipfile:7]: I don't think that'll work - see https://github.com/awslabs/cdk8s/blob/5759d0d927268bb4e9cb9ba01d13053b44834fed/docs/getting-started/python.md#prerequisites

File: packages/cdktf-cli/lib/get/base.ts [hunk 2]
```diff
@@ -48,7 +48,7 @@ export abstract class GetBase {
         });
 
         const pacmak = require.resolve('jsii-pacmak/bin/jsii-pacmak');
-        await shell(pacmak, [ '--target', options.targetLanguage, '--code-only' ]);
+        await shell('node', [ pacmak, '--target', options.targetLanguage, '--code-only' ]);
```
Comment (skorfmann) [inline packages/cdktf-cli/lib/get/base.ts:51]: According to [this comment](https://github.com/awslabs/cdk8s/pull/183), it might be worthwhile implementing https://github.com/aws/jsii-srcmak rather than fixing this here.

File: packages/cdktf-cli/templates/python/cdktf.json [hunk 3]
```diff
@@ -1,6 +1,6 @@
 {
   "language": "python",
-  "app": "pipenv run ./main.py",
+  "app": "pipenv run python main.py",
```
Comment (skorfmann) [inline packages/cdktf-cli/templates/python/cdktf.json:3]: That's cross platform compatible?

File: packages/cdktf-cli/templates/python/Pipfile (hunk 1 above)
Comment (jsteinich) [reply packages/cdktf-cli/templates/python/Pipfile:7]: We might want to remove entirely then or switch away from pipenv since something like ">=3.7" isn't supported.

File: packages/cdktf-cli/lib/get/base.ts (hunk 2 above)
Comment (jsteinich) [reply packages/cdktf-cli/lib/get/base.ts:51]: I saw you mentioned that elsewhere. I'm not really familiar with what that entails, but I can take a look.

Comment (skorfmann) [reply packages/cdktf-cli/lib/get/base.ts:51]: see #272

File: packages/cdktf-cli/templates/python/cdktf.json (hunk 3 above)
Comment (jsteinich) [reply packages/cdktf-cli/templates/python/cdktf.json:3]: It worked in the two platforms I tested on.
On *nix systems the shebang line allows for switching the interpreter. On Windows that doesn't work, so explicit specification is generally necessary.

File: packages/cdktf-cli/templates/python/Pipfile (hunk 1 above)
Comment (skorfmann) [reply packages/cdktf-cli/templates/python/Pipfile:7]: Hm, when looking at the [jsii build config](https://github.com/aws/jsii/blob/6ea8daa8a022c5bda5fd1854d49292e65caac2be/.github/workflows/main.yml) it looks like at least 3.6 - 3.8 should work. And according to [this](https://www.python.org/downloads/) 3.5 won't be supported soon. 

Screenshot 2020-07-31 at 16 15 14

@eladb are there docs which specify Python version support for `jsii`?

**Comment by skorfmann** [comment]
@jsteinich Do you think this might be easier now since #276 got merged?

**Comment by jsteinich** [comment]
> @jsteinich Do you think this might be easier now since #276 got merged?

Doesn't really change much since I had worked around some of the things it fixed, but I was waiting on it.
I should hopefully get this working in the next few days.

File: packages/cdktf-cli/templates/python/Pipfile (hunk 1 above)
Comment (skorfmann) [reply packages/cdktf-cli/templates/python/Pipfile:7]: Well, let's just go with the major version then. Seems to work fine.

**Review by skorfmann — APPROVED** [review]
