### PR TITLE
fix(lib): Fix handling of replaceTriggeredBy lifecycle attribute

### LINKED ISSUE #2082: Support of `replace_triggered_by` lifecycle
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Would you please consider adding support of `replace_triggered_by` lifecycle

### References
[Terraform Docs](https://www.terraform.io/language/meta-arguments/lifecycle#replace_triggered_by)

### LINKED ISSUE #3196: lifecycle: replaceTriggeredBy faulty
### Expected Behavior

When adding lifecycle.replaceTriggeredBy with an ITerraformDependable cdktf should generate valid terraform.

### Actual Behavior

After adding lifecycle.replaceTriggeredBy with an ITerraformDependable cdktf generates invalid terraform.

    "lifecycle": {
      "replace_triggered_by": [
        "${azurerm_subnet.network_default_subnet_6830CB96}"
      ]
    },

The terraform seems to be invalid because string interpolation seems not to be intended for that parameter.

### Steps to Reproduce

Add lifecycle.replaceTriggeredBy with an ITerraformDependable to a resource in typescript.

    lifecycle: {
      replaceTriggeredBy: [iTerraformDependable]
    }

### Versions

language: typescript
cdktf-cli: 0.19.0
node: v18.13.0
cdktf: 0.19.0
constructs: 10.3.0
jsii: null
terraform: 1.5.2
arch: x64
os: win32 10.0.22000

### Providers

┌───────────────┬──────────────────┬───────┬────────────┬──────────────┬─────────────────┐
│ Provider Name │ Provider Version │ CDKTF │ Constraint │ Package Name │ Package Version │
├───────────────┼──────────────────┼───────┼────────────┼──────────────┼─────────────────┤
│ azurerm       │ 3.76.0           │       │ ~> 3.70    │              │                 │
├───────────────┼──────────────────┼───────┼────────────┼──────────────┼─────────────────┤
│ random        │ 3.5.1            │       │ ~> 3.5     │              │                 │
├───────────────┼──────────────────┼───────┼────────────┼──────────────┼─────────────────┤
│ elastic/ec    │ 0.9.0            │       │ ~> 0.9     │              │                 │
├───────────────┼──────────────────┼───────┼────────────┼──────────────┼─────────────────┤
│ Azure/azapi   │ 1.9.0            │       │ ~> 1.9     │              │                 │
└───────────────┴──────────────────┴───────┴────────────┴──────────────┴─────────────────┘

### Gist

_No response_

### Possible Solutions

_No response_

### Workarounds

I tried the [escape hatch](https://developer.hashicorp.com/terraform/cdktf/concepts/resources#escape-hatch) but ultimately had the same issue.

### Anything Else?

_No response_

### References

_No response_

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by ansgarm**
Resolves #3196
Resolves #2082

### CODE REVIEW

File: packages/cdktf/lib/terraform-resource.ts [hunk 1]
```diff
@@ -50,6 +50,32 @@ export interface TerraformResourceLifecycle {
...
+  lifecycle?: TerraformResourceLifecycle
+): TerraformResourceLifecycle | undefined {
+  if (!lifecycle) {
+    return undefined;
+  }
+
+  return {
+    ...lifecycle,
+    ...(lifecycle?.replaceTriggeredBy?.length && {
+      replaceTriggeredBy: lifecycle?.replaceTriggeredBy?.map((x) => {
```
Comment (DanielMSchmidt) [inline packages/cdktf/lib/terraform-resource.ts:68]: Nit: I'd prefer a ternary. The && makes it look brittle to me, I think my frontend instincts are kicking in

**Review by DanielMSchmidt — APPROVED** [review]
