### PR TITLE
fix(hcl2cdk): handle no providers passed and add cdktf import for remote state data sources

### LINKED ISSUE #1548: Converted remote state data sources fail to synth
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

- cdktf 0.9

### Actual Behavior

Running `cdktf convert` on the test cases in [hcl2cdk.test.ts](https://github.com/hashicorp/terraform-cdk/tree/main/packages/@cdktf/hcl2cdk/test/hcl2cdk.test.ts) tagged with `Synth.needsAFix_MissingCdktfImport` will result in an error. It seems like remote state data sources don't lead to the `import * as cdktf from "cdktf";` line being added

### Steps to Reproduce

Change `Synth.needsAFix_MissingCdktfImport` in the tests to `Synth.yes` and observe the errors

### References

- https://github.com/hashicorp/terraform-cdk/pull/1539

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
Closes #1548

### CODE REVIEW

File: packages/@cdktf/provider-generator/lib/get/generator/provider-schema.ts [hunk 1]
```diff
@@ -205,6 +205,16 @@ export async function readSchema(targets: ConstructsMakerTarget[]) {
     terraform: {},
   };
 
+  if (targets.length === 0) {
+    return {
+      providerSchema: {
+        format_version: "1.0" as "1.0",
```
Comment (ansgarm) [inline packages/@cdktf/provider-generator/lib/get/generator/provider-schema.ts:211]: Is this required? 😅 `as "1.0"`?

**Review by ansgarm — APPROVED** [review]

File: packages/@cdktf/provider-generator/lib/get/generator/provider-schema.ts (hunk 1 above)
Comment (ansgarm) [reply packages/@cdktf/provider-generator/lib/get/generator/provider-schema.ts:211]: Ah, thanks for the explanation!
