### PR TITLE
fix(hcl2cdk): ensure we take the same resource name as the provider generator does

### LINKED ISSUE #1552: Convert does not rename resources the same way as the provider generator does
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

- cdktf 0.9

### Actual Behavior

Running `cdktf convert` on the test cases in [hcl2cdk.test.ts](https://github.com/hashicorp/terraform-cdk/tree/main/packages/@cdktf/hcl2cdk/test/hcl2cdk.test.ts) tagged with `Synth.needsAFix_UnforseenClassRename` will result in an error. It seems like we rename classes to avoid duplication, but this renaming is not known to convert.

### Steps to Reproduce

Change `Synth.needsAFix_UnforseenRename` in the tests to `Synth.yes` and observe the errors

### References

- https://github.com/hashicorp/terraform-cdk/pull/1539

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
Closes #1552

### CODE REVIEW

File: packages/@cdktf/provider-generator/lib/index.ts [hunk 1]
```diff
@@ -18,16 +18,21 @@ import * as srcmak from "jsii-srcmak";
...
+import { ProviderSchema } from "./get/generator/provider-schema";
+
 export { setLogger } from "./config";
+export { TerraformProviderGenerator, CodeMaker };
 
 // Used for testing only
 export async function generateProviderBindingsFromSchema(
   targetPath: string,
-  schemaJSON: any,
+  schemaJSON: ProviderSchema,
```
Comment (ansgarm) [inline packages/@cdktf/provider-generator/lib/index.ts:29]: nice

**Review by ansgarm — APPROVED** [review]
Nice work!
