### PR TITLE
fix: Map keys not being quoted when they are not valid identifiers

### LINKED ISSUE #3459: Tags do not properly translate when doing cdktf synth --hcl
### Expected Behavior

resource "aws_rds_cluster" "my-cluster" {
  backup_retention_period = 5
  cluster_identifier      = "my-cluster"
  engine                  = "aurora-postgresql"
  preferred_backup_window = "05:00-07:00"
  skip_final_snapshot     = true
  tags = {
    "x:y" = "z:a"
  }
}

### Actual Behavior

resource "aws_rds_cluster" "my-cluster" {
  backup_retention_period = 5
  cluster_identifier      = "my-cluster"
  engine                  = "aurora-postgresql"
  preferred_backup_window = "05:00-07:00"
  skip_final_snapshot     = true
  tags = {
    x : y = "z:a"
  }
}

### Steps to Reproduce

1. Define an RDS cluster in Python CDKTF

```
RdsCluster(
        stack,
        "my-cluster",
        cluster_identifier="my-cluster",
        engine="aurora-postgresql",
        backup_retention_period=5,
        preferred_backup_window="05:00-07:00",
        skip_final_snapshot=True,
        tags={
               "x:y": "z:a"
        },
    )
```

2. cdktf synth --hcl

3. Look at .tf output. Notice the keys for tags are missing quotations and the tags map itself is malformed

### Versions

cdktf 0.20.1

### Providers

_No response_

### Gist

_No response_

### Possible Solutions

_No response_

### Workarounds

_No response_

### Anything Else?

_No response_

### References

_No response_

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by mutahhir**
### Related issue

Fixes #3459

### Description

Terraform expects keys of maps to be [valid identifiers](https://developer.hashicorp.com/terraform/language/syntax/configuration#identifiers), and the HCL synth was not ensuring that before. This PR tries to detect areas where quoting is required to ensure valid HCL is output.

### CODE REVIEW

File: packages/cdktf/lib/hcl/render.ts [hunk 1]
```diff
@@ -15,6 +15,14 @@ function escapeQuotes(str: string): string {
   return str.replace(/(?<!\\)"/g, '\\"');
 }
 
+function wrapIdentifierInQuotesIfNeeded(key: string): string {
+  return /^(?:\d|[\-])/.test(key)
```
Comment (DanielMSchmidt) [inline packages/cdktf/lib/hcl/render.ts:19]: Nit picking, but can't these be combined? Also wouldn't it be easier to test if a key is an identifier by using the logic [described in the docs](https://developer.hashicorp.com/terraform/language/syntax/configuration#identifiers) and quote in all other cases?

```suggestion
  return (/^(?:\d|[\-])/.test(key) || /[^A-Za-z0-9_\-]/.test(key)) ? `"${key}"` : key
```

File: packages/cdktf/lib/hcl/render.ts [hunk 2]
```diff
@@ -163,7 +171,11 @@ export function renderMap(map: any): string {
   }
   return `{
 ${Object.entries(map)
-  .map(([k, v]) => `${k} = ${renderMapValue(v)}`)
+  .map(([k, v]) => {
+    const wrappedKey = wrapIdentifierInQuotesIfNeeded(k);
+
+    return `${wrappedKey} = ${renderMapValue(v)}`;
```
Comment (DanielMSchmidt) [inline packages/cdktf/lib/hcl/render.ts:177]: Nit: Could stay one line :)

**Review by ansgarm — APPROVED** [review]

**Review by DanielMSchmidt — APPROVED** [review]
Just a few nits :)

File: packages/cdktf/lib/hcl/render.ts (hunk 1 above)
Comment (mutahhir) [reply packages/cdktf/lib/hcl/render.ts]: Yeah, I think you're right. I just got caught in the middle of my thought process where I didn't want to use `A-Za-z` detection because of unicode. I didn't find groups to use that were more unicode friendly, so ended up using it anyway and didn't further reduce everything.
