### PR TITLE
fix(cli): dont upload .terraform folders

### LINKED ISSUE #711: Switching from local to cloud execution causes error
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

- CDKTF: 0.3.0

### Expected Behavior

- No error in terraform cloud

### Actual Behavior

The Terraform Cloud run fails with:

```
Terraform v0.15.3
on linux_amd64

Setup failed: failed unpacking terraform config: illegal slug error: invalid symlink (".terraform/providers/registry.terraform.io/hashicorp/null/3.1.0/darwin_amd64" -> "../../../../../../../../../../../.terraform.d/plugin-cache/registry.terraform.io/hashicorp/null/3.1.0/darwin_amd64") has external target
```

### Steps to Reproduce

1. Create a project based on the local template
2. Deploy and destroy resources
3. Change to cloud run and apply, the error will happen

### Workaround

Removing the `cdktf.out` folder helps (thanks @ansgarm), it seems like terraform init leaves symlinks that can not be uploaded.

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
Closes #711

### CODE REVIEW

**Review by ansgarm — APPROVED** [review]

File: packages/cdktf-cli/bin/cmds/ui/models/terraform-cloud.ts [hunk 1]
```diff
@@ -127,6 +130,8 @@ export class TerraformCloud implements Terraform {
 
     this.configurationVersionId = version.id
 
+    this.removeLocalTerraformDirectory()
```
Comment (ansgarm) [inline packages/cdktf-cli/bin/cmds/ui/models/terraform-cloud.ts:133]: There are two modes for Terraform Cloud: local execution and remote execution. Could this possibly break local execution or be unwanted (as it destroys the local cache containing already initialized Terraform providers)? 🤔

Comment (DanielMSchmidt) [reply packages/cdktf-cli/bin/cmds/ui/models/terraform-cloud.ts:133]: I would guess no as this is the terraform cloud implementation of this function. The Cli implementation would need to be able to deal with a blank state so it should work IMHO

Comment (skorfmann) [reply packages/cdktf-cli/bin/cmds/ui/models/terraform-cloud.ts:133]: Yeah, I think this should be ok - since that's scoped to the stack anyway. Even if you had multiple stacks targeting local and cloud, it should still be ok.

**Review by skorfmann — APPROVED** [review]
