### PR TITLE
Fix module variables without type

### LINKED ISSUE #596: Custom module variables without type fail to import with cdktf
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

using `typescript@4.2.3` and `cdktf 0.2.0`

### Affected Resource(s)

cdktf importing of custom modules

### Debug Output

i'm using the new module improvements from #584 to source modules locally and from github. It is works as expected unless a module's variables do not have a type specified. cdktf fails to import those modules. Adding type to the variables allows cdktf to successfully import modules.

[error gist](https://gist.github.com/celliott/9ee102bbc4839ab3294ded957abb29f6)

**example terraformModules**

```
"terraformModules": [
  {
    "name": "s3",
    "source": "git@github.com:mycompany/terraform-aws-s3.git"
  }
],
```

### Expected Behavior

I would expect either:
1. if type not set, then use `any`
or
2. better error handling so it is obvious what is wrong
 

### Actual Behavior

cdktf throws obtuse error when variables don't have type. it may make sense to force type since that is desired for ts. another option would be to assume `any` if type not set.

### Steps to Reproduce

import a custom module with a variable without a type.

```
variable "my_var" {
  description = "My example var without type set"
}
```

### Important Factoids

terraform defaults to `any` if type not set

### References

https://www.terraform.io/docs/language/values/variables.html#type-constraints
>If no type constraint is set then a value of any type is accepted.

### LINKED ISSUE #613: cdktf get fails with "TypeError: Cannot read property 'match' of undefined" using google module
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

Node 14.6.0
Python 3.7.3
Terraform 0.14.9
cdktf 0.2.0 and 0.2.1 (NOTE: issue is **not** present in 0.1.0)

### Affected Resource(s)

Module: terraform-google-modules/network/google

### Debug Output

Full debug output here: https://gist.githubusercontent.com/alexjmoore/e0554867c194af530ae9f92ccd15bcc4/raw/48e309902ff60aa784d7e9ff8a4cf3a76b545693/gistfile1.txt

### Expected Behavior

I would expect cdktf to pull in the modules without issue.

### Actual Behavior

`cdktf get` results in:

```
[2K[1A[2K[G⠸ downloading and generating modules and providers...
[2K[1A[2K[GTypeError: Cannot read property 'match' of undefined
    at transformVariables (/usr/lib/node_modules/cdktf-cli/lib/get/generator/provider-schema.js:43:46)
    at harvestModuleSchema (/usr/lib/node_modules/cdktf-cli/lib/get/generator/provider-schema.js:89:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /usr/lib/node_modules/cdktf-cli/lib/get/generator/provider-schema.js:133:28
    at async Object.withTempDir (/usr/lib/node_modules/cdktf-cli/lib/util.js:41:9)
    at async Object.readSchema (/usr/lib/node_modules/cdktf-cli/lib/get/generator/provider-schema.js:124:5)
    at async ConstructsMaker.generateTypeScript (/usr/lib/node_modules/cdktf-cli/lib/get/constructs-maker.js:160:24)
    at async ConstructsMaker.generate (/usr/lib/node_modules/cdktf-cli/lib/get/constructs-maker.js:174:9)
    at async get (/usr/lib/node_modules/cdktf-cli/bin/cmds/ui/get.js:50:17)
⠸ downloading and generating modules and providers...
Cannot read property 'match' of undefined
```

### Steps to Reproduce

Use the following `cdktf.json`:

```
{
  "language": "python",
  "app": "python3 ./main.py",
  "terraformProviders": ["google@~>3.0"],
  "terraformModules": ["terraform-google-modules/network/google@3.0.0"],
  "codeMakerOutput": "imports",
  "context": {
    "excludeStackIdFromLogicalIds": "true",
"allowSepCharsInLogicalIds": "true"
  }
}
```

### References

* #0000

### PR DESCRIPTION
**Pull request by jsteinich**
Fixes #596 
Likely fixes #613, but I haven't verified.

I also put in handling for default type number since I had written my test with that. There are probably other default types that could be correctly inferred, but that's another matter.

Finally, pulled out a test helper function to make additional module generation tests easy to add.

### CODE REVIEW

File: packages/cdktf-cli/test/get/util.ts [hunk 1]
```diff
@@ -28,4 +28,29 @@ export function expectImportMatchSnapshot(constraint: TerraformDependencyConstra
       expect(manifest).toMatchSnapshot();
     });
   });
+}
+
+export function expectModuleToMatchSnapshot(testName: string, testCategory: string, fixtureName: string) {
+  test(testName, async () => {
```
Comment (ansgarm) [inline packages/cdktf-cli/test/get/util.ts:34]: I really like pulling this out into a separate function!
I'm a bit unsure whether I'd pull the `test()` function into it as well. I like the upside of being able to add other `test()` statements later on to all of those tests at once.
However at first I'd have expected a `test()` in the test file itself and was confused to find `expectModuleToMatchSnapshot()` as it looks very similar to the other matchers from jest / `expect`. Maybe some other naming using `createTest` or another verb would have helped me.
Just a comment as it came to mind, I don't have hard feelings on this but I thought I'd rather share than not 😅

Comment (jsteinich) [reply packages/cdktf-cli/test/get/util.ts:34]: I started to make it as just a function that would be passed into `test()`, but then noticed the existing method and decided to follow suit.

Having it create the test does seem reasonable since it includes an `expect()` call, but renaming might be a good idea. Perhaps `testThatModuleMatchesSnapshot`. 🤷

Comment (ansgarm) [reply packages/cdktf-cli/test/get/util.ts:34]: Ah, I didn't notice there already being a similar named function. Let's just keep it like it is then. Sorry for the noise 💬😅

**Review by ansgarm — APPROVED** [review]
