### PR TITLE
Make sure tokens resolved before converting to json

### LINKED ISSUE #256: Token asAny / Intrinsic value doesn't work as expected
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
0.0.12

### Affected Resource(s)
Referenced remote state

### Debug Output
https://github.com/hashicorp/terraform-cdk/pull/241/checks?sha=46584d718d9a955732949782d0638e2dd5c8c1c7

### Expected Behavior
The `creation_stack` property should probably just be removed in tests since it is very sensitive to unrelated changes

### Actual Behavior
Despite removing hard paths, the `creation_stack` was different with both local and runner using the docker image.

### Steps to Reproduce
Run yarn test with https://github.com/hashicorp/terraform-cdk/pull/241

### References

* #241

### LINKED ISSUE #433: creationStack gets generated for certain scenarios
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf 0.0.18, TypeScript

### Affected Resource(s)

I've seen this happening on Tags so far.

### Expected Behavior

creationStack should be omitted as it makes the terraform stack too verbose.

### Actual Behavior

creationStack gets printed for certain resources, sample: https://gist.github.com/choweiyuan/66b82ddcbda96b6d51f71d1e77fa4ed2

### Steps to Reproduce

```
class DBOptionGroup extends TerraformStack {
  constructor(scope: Construct, name: string) {
    super(scope, name);

    const tags: { [key: string]: string } = {};
    const sampleTagKey = new TerraformVariable(this, "sampleTagKey", {
      type: "string",
      description: "Sample tag key",
    })
    const sampleTagValue = new TerraformVariable(this, "sampleTagValue", {
      type: "string",
      description: "Sample tag value"
    })
    tags[sampleTagKey.value] = sampleTagValue.value
    const majorEngineVersion = "12.1";
    const engine = "oracle-se2";

    new DbOptionGroup(this, "dbOptionGroup2", {
      engineName: engine,
      majorEngineVersion,
      tags
    })
  }
}

const app = new App({
  stackTraces: false
});
new DBOptionGroup(app, 'sampleStack');

app.synth();
```

### Important Factoids

If I hardcode the tag key/value pair, then creationStack wouldn't appear. If I use variable then the problem occurs.

### References

* #0000

### LINKED ISSUE #437: Incorrect Terraform (String) Variable Documentation
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
cdktf 0.0.18, TypeScript

### Affected Resource(s)
Terraform Variables, AWS Tags

### Expected Behavior

cdktf synth should produce a cdktf.tf.json file that works 

### Actual Behavior

cdktf synth produces a file that's not usable and throws error when running terraform plan

### Steps to Reproduce

```
class DBOptionGroup extends TerraformStack {
  constructor(scope: Construct, name: string) {
    super(scope, name);

    const tags: { [key: string]: string } = {};
    const sampleTagKey = new TerraformVariable(this, "sampleTagKey", {
      type: "string",
      description: "Sample tag key",
    })
    const sampleTagValue = new TerraformVariable(this, "sampleTagValue", {
      type: "string",
      description: "Sample tag value"
    })
    tags[sampleTagKey.value] = sampleTagValue.value
    const majorEngineVersion = "12.1";
    const engine = "oracle-se2";

    new DbOptionGroup(this, "dbOptionGroup2", {
      engineName: engine,
      majorEngineVersion,
      tags
    })
  }
}

const app = new App({
  stackTraces: false
});
new DBOptionGroup(app, 'sampleStack');

app.synth();
```
### Important Factoids

Issue occurs when I'm trying to use terraformValue
```
    tags[sampleTagKey.value] = sampleTagValue.value
```
Then it outputs https://gist.github.com/choweiyuan/66b82ddcbda96b6d51f71d1e77fa4ed2#file-cdk-tf-json-L24-L41

Whereas I'm just expecting
```
          "${var.sampleStack_sampleTagKey_F41F6D4C}": "${var.sampleStack_sampleTagValue_278ED4D5}",
```
I was basing it example from here  https://github.com/hashicorp/terraform-cdk/blob/master/docs/working-with-cdk-for-terraform/terraform-variables.md 
```
const imageId = new TerraformVariable(this, 'imageId', {
    type: 'string',
    default: 'ami-abcde123',
    description: 'What AMI to use to create an instance'
});
new Instance(this, 'hello', {
  ami: imageId.value,
  instanceType: 't2.micro'
});
```
Where it uses `imageId.value`. If its changed to `imageId.stringValue` I think it should work fine. So I'm raising this as just a documentation issue at the moment

### References
https://github.com/hashicorp/terraform-cdk/blob/master/docs/working-with-cdk-for-terraform/terraform-variables.md

* #0000

### PR DESCRIPTION
**Pull request by jsteinich**
Fixes #433.
Fixes #437.
Fixes #256.

Need to resolve tokens before converting to terraform json to prevent the Intrinsic's creation stack from being included. This matches the behavior of the AWS CDK.

I also updated a couple tests to check this behavior and to match the documentation for the associated features.

### CODE REVIEW

File: packages/cdktf/lib/terraform-stack.ts [hunk 1]
```diff
@@ -151,3 +146,18 @@ export class TerraformStack extends Construct {
...
 }
+
+function terraformElements(node: IConstruct, into: TerraformElement[] = []): TerraformElement[] {
+  if (node instanceof TerraformElement) {
+    into.push(node);
+  }
+
+  for (const child of Node.of(node).children) {
+    // Don't recurse into a substack
+    if (TerraformStack.isStack(child)) { continue; }
```
Comment (skorfmann) [inline packages/cdktf/lib/terraform-stack.ts:157]: Is this aiming at nested stacks? Do you have an example what this is about?

File: packages/cdktf/lib/terraform-stack.ts [hunk 2]
```diff
@@ -129,18 +129,13 @@ export class TerraformStack extends Construct {
       }
     };
 
-    const visit = (node: IConstruct) => {
-      if (node instanceof TerraformElement) {
-        deepMerge(tf,  node.toTerraform());
-      }
+    const elements = terraformElements(this);
+    const fragments = elements.map(e => resolve(this, e.toTerraform()));
```
Comment (skorfmann) [inline packages/cdktf/lib/terraform-stack.ts:133]: do we have to call it for each element?

File: packages/cdktf/lib/terraform-stack.ts (hunk 1 above)
Comment (jsteinich) [reply packages/cdktf/lib/terraform-stack.ts:157]: Yeah, this would be for nested stacks. Could just remove since we don't have them. I was just porting some changes from AWS CDK.

Comment (skorfmann) [reply packages/cdktf/lib/terraform-stack.ts:157]: right ok - well, if it works let's keep it. We'll likely need that for #35

File: packages/cdktf/lib/terraform-stack.ts (hunk 2 above)
Comment (jsteinich) [reply packages/cdktf/lib/terraform-stack.ts:133]: Technically no; however, the act of merging clobbers information necessary to resolve an intrinsic, so this seems like the cleanest way of accomplishing that (also how AWS CDK does it). 

It might make sense to resolve the `rawOverrides`, but I wouldn't expect tokens to exist there.

I'm not entirely sure if the final `resolve` is necessary, but AWS CDK has it and it seems like a good safeguard.

Comment (skorfmann) [reply packages/cdktf/lib/terraform-stack.ts:133]: cool - thanks for elaborating 👍

**Review by skorfmann — APPROVED** [review]
