### PR TITLE
fix(lib): improve error messages for token resolution

### LINKED ISSUE #1890: Make `Found an encoded list token string in a scalar string context` easier to debug
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently those errors come with stack traces like this:

```
    /Users/danielschmidt/work/demos/cdktf-aws-networking-demo/node_modules/cdktf/lib/tokens/private/resolve.ts:127
          throw new Error(
                ^
    Error: Found an encoded list token string in a scalar string context. Use 'Fn.element(list, 0)' (not 'list[0]') to extract elements from token lists
        at resolve (/Users/danielschmidt/work/demos/cdktf-aws-networking-demo/node_modules/cdktf/lib/tokens/private/resolve.ts:127:13)
        at Object.resolve (/Users/danielschmidt/work/demos/cdktf-aws-networking-demo/node_modules/cdktf/lib/tokens/private/resolve.ts:70:16)
        at resolve (/Users/danielschmidt/work/demos/cdktf-aws-networking-demo/node_modules/cdktf/lib/tokens/private/resolve.ts:244:39)
        at Object.resolve (/Users/danielschmidt/work/demos/cdktf-aws-networking-demo/node_modules/cdktf/lib/tokens/private/resolve.ts:70:16)
        at resolve (/Users/danielschmidt/work/demos/cdktf-aws-networking-demo/node_modules/cdktf/lib/tokens/private/resolve.ts:244:39)
        at Object.resolve (/Users/danielschmidt/work/demos/cdktf-aws-networking-demo/node_modules/cdktf/lib/tokens/private/resolve.ts:70:16)
        at resolve (/Users/danielschmidt/work/demos/cdktf-aws-networking-demo/node_modules/cdktf/lib/tokens/private/resolve.ts:244:39)
        at Object.resolve (/Users/danielschmidt/work/demos/cdktf-aws-networking-demo/node_modules/cdktf/lib/tokens/private/resolve.ts:70:16)
        at Object.resolve (/Users/danielschmidt/work/demos/cdktf-aws-networking-demo/node_modules/cdktf/lib/tokens/private/resolve.ts:244:39)
        at Function.resolve (/Users/danielschmidt/work/demos/cdktf-aws-networking-demo/node_modules/cdktf/lib/tokens/token.ts:244:12)

```

Adding information like which construct / property caused the error would be great, especially for users changing a lot of code at once, it's super hard to pin point where the error stems from

### LINKED ISSUE #2254: Hint to `TerraformIterators` in error message when accessing list token elements
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When calling e.g. `Array.map` or `Array.forEach` on a list token, we currently print this error message:

> Error: Found an encoded list token string in a scalar string context. Use 'Fn.element(list, 0)' (not 'list[0]') to extract elements from token lists

While this message is fitting when users try to access an index of a list token, it is not as helpful in the aforementioned case.
We should extend the hint in the error message to include a reference to iterators in case they might've used `.map` or similar.
We could even link a new docs page about this error message and add full examples for these two cases (and possibly more) with proposals what do use instead.

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
Closes #2254
Closes #1890

### CODE REVIEW

File: packages/cdktf/lib/tokens/private/resolve.ts [hunk 1]
```diff
@@ -21,6 +21,32 @@ import {
 import { TokenMap } from "./token-map";
 import { Token } from "../token";
 
+const LIST_ERROR_EXPLANATION = `In CDKTF we represent lists where the value is only known at runtime (versus compile / synth time) as
+Arrays with a single element that is a string token, e.g. ["Token.1"]. This is because at compile time we
+don't know the length of the list, so far CDKTF did not invoke Terraform to communicate with the cloud provider.
+This is done at a later stage on the synthesized static JSON file.
+As we don't know the length of the list not the content we can not differenciate if the list was accessed at the first index,
```
Comment (ansgarm) [inline packages/cdktf/lib/tokens/private/resolve.ts:28]:
```suggestion
As we don't know the length of the list not the content we can not differentiate if the list was accessed at the first index,
```

File: packages/cdktf/lib/tokens/private/resolve.ts [hunk 2]
```diff
@@ -21,6 +21,32 @@ import {
...
+the last index, or as part of a loop. To avoid this ambiguity:
+
+- If you want to access a singular item use 'Fn.element(list, 0)' (not 'list[0]')
+- If you want to loop over the list use 'TerraformIterator.fromList(list)' (not 'for (const item of list)' or 'list.forEach(item => ...)')
+
+To learn more about tokens see https://developer.hashicorp.com/terraform/cdktf/concepts/tokens
+To learn more about iterators see https://developer.hashicorp.com/terraform/cdktf/concepts/iterators`;
+
+const MAP_ERROR_EXPLANATION = `In CDKTF we represent maps where the value is only known at runtime (versus compile / synth time) as
+Objects with a single key-value pair where the value is a string token, e.g. { "&{TfToken[Token.1]}": "String Map Token Value" }. This is because at compile time we
```
Comment (ansgarm) [inline packages/cdktf/lib/tokens/private/resolve.ts:38]:
```suggestion
pbjects with a single key-value pair where the value is a string token, e.g. { "&{TfToken[Token.1]}": "String Map Token Value" }. This is because at compile time we
```

also: "where the value is a string token" + your example has the token in the key – Is it the key or the value that holds the token?

File: packages/cdktf/lib/tokens/private/resolve.ts [hunk 3]
```diff
@@ -21,6 +21,32 @@ import {
...
+don't know the contents of the map, so far CDKTF did not invoke Terraform to communicate with the cloud provider.
```
Comment (ansgarm) [inline packages/cdktf/lib/tokens/private/resolve.ts:39]: > so far CDKTF […]

Is there a word missing? Maybe "as"? Still sounds a bit weird. (This also applies to the error message above, which shares this wording).

File: packages/cdktf/lib/tokens/private/resolve.ts [hunk 4]
```diff
@@ -21,6 +21,32 @@ import {
...
+This is done at a later stage on the synthesized static JSON file.
+As we don't know the contents of the map we do not know which key was accessed, or if the map was accessed as part of a loop.
+To avoid this ambiguity:
+
+- If you want to access a singular item use 'Fn.lookup(map, key, default)' (not 'map[key]')
```
Comment (ansgarm) [inline packages/cdktf/lib/tokens/private/resolve.ts:44]:
```suggestion
- If you want to access a singular item use 'Fn.lookup(map, key)' (not 'map[key]')
```
Default is optional now, we render the `map[key]` expression if there was no default passed.

File: packages/cdktf/lib/tokens/private/resolve.ts [hunk 5]
```diff
@@ -119,7 +146,8 @@ export function resolve(obj: any, options: IResolveOptions): any {
 
   if (typeof obj === "function") {
     throw new Error(
-      `Trying to resolve a non-data object. Only token are supported for lazy evaluation. Path: ${pathName}. Object: ${obj}`
+      `Trying to resolve a non-data object (e.g. a function) at '${pathName}': ${obj}. Only token are supported for lazy evaluation.
```
Comment (ansgarm) [inline packages/cdktf/lib/tokens/private/resolve.ts:149]:
```suggestion
      `Trying to resolve a non-data object (e.g. a function) at '${pathName}': ${obj}. Only tokens are supported for lazy evaluation.
```

File: packages/cdktf/lib/tokens/private/resolve.ts [hunk 6]
```diff
@@ -119,7 +146,8 @@ export function resolve(obj: any, options: IResolveOptions): any {
...
+If you want to have a lazy value computed, please use the Lazy class, e.g. Lazy.stringValue({ produce: () => "Hello World" })`
```
Comment (ansgarm) [inline packages/cdktf/lib/tokens/private/resolve.ts:150]:
```suggestion
If you want to have a lazily computed value, please use the Lazy class, e.g. Lazy.stringValue({ produce: () => "Hello World" })`
```

File: packages/cdktf/lib/tokens/private/resolve.ts [hunk 7]
```diff
@@ -176,7 +204,7 @@ export function resolve(obj: any, options: IResolveOptions): any {
   if (typeof obj === "number") {
     if (obj === Token.NUMBER_MAP_TOKEN_VALUE) {
       throw new Error(
-        "Found an encoded map token in a scalar number context. Use 'Fn.lookup(map, key, default)' (not 'map[key]') to extract values from token maps."
+        `Found an encoded map token in a scalar number context. ${MAP_ERROR_EXPLANATION}`
```
Comment (ansgarm) [inline packages/cdktf/lib/tokens/private/resolve.ts:207]: No newline here? Seems inconsistent with the messages above 🤓

**Review by ansgarm — COMMENTED** [review]
Just a few typos ✌️ Looks good otherwise 💯

File: packages/cdktf/lib/tokens/private/resolve.ts (hunk 3 above)
Comment (DanielMSchmidt) [reply packages/cdktf/lib/tokens/private/resolve.ts:39]: I think it's grammatically okay since I am chaining two full sentences with a comma which I think is correct. Maybe making it two sentences would be better, what do you think @Maed223

Comment (Maed223) [reply packages/cdktf/lib/tokens/private/resolve.ts:39]: Looks fine grammatically, it just reads a bit ambiguously since the relationship between the two parts isn't very clear. Think it'd help to more explicitly relate the second part as the reason why the first part is true–

```
This is because the length of the list isn't know at compile time, as CDKTF has not yet invoked Terraform to communicate with the cloud provider. This is done at a later stage in the synthesization of the static JSON file.
```

Or something along those lines 🙂

File: packages/cdktf/lib/tokens/private/resolve.ts [hunk 8]
```diff
@@ -92,9 +118,10 @@ export function resolve(obj: any, options: IResolveOptions): any {
 
   // protect against cyclic references by limiting depth.
   if (prefix.length > 200) {
-    throw new Error(
-      "Unable to resolve object tree with circular reference. Path: " + pathName
-    );
+    throw new Error(`Unable to resolve object tree with circular reference at '${pathName}'.
+This error is thrown if the depth of the object tree is greater than 200 to protect against cyclic references.
+To resolve this inspect the construct creating the cyclic reference (most likely in '${pathName}') and make sure
+it does not create an infinite construct nesting.`);
```
Comment (Maed223) [inline packages/cdktf/lib/tokens/private/resolve.ts:124]:
```suggestion
it does not create an infinite nesting of constructs.`);
```
nit, feel free to disregard

File: packages/cdktf/lib/tokens/private/resolve.ts [hunk 9]
```diff
@@ -234,15 +263,17 @@ export function resolve(obj: any, options: IResolveOptions): any {
   // mistake somewhere and resolve will get into an infinite loop recursing into
   // child.parent <---> parent.children
   if (isConstruct(obj)) {
-    throw new Error("Trying to resolve() a Construct at " + pathName);
+    throw new Error(`Trying to resolve() a Construct at '${pathName}'. 
+This often means that there is an unintended cyclic dependency in your construct tree.
+This leads to the resolution being stuck in an infinite loop and will eventually fail.`);
```
Comment (Maed223) [inline packages/cdktf/lib/tokens/private/resolve.ts:268]:
```suggestion
throw new Error(`Trying to resolve() a Construct at '${pathName}'. 
This often means that there is an unintended cyclic dependency in your construct tree, leading to the resolution being stuck in an infinite loop which will eventually fail.`);
```

Another nit- feel free to ignore

File: packages/cdktf/lib/tokens/private/resolve.ts (hunk 3 above)
Comment (DanielMSchmidt) [reply packages/cdktf/lib/tokens/private/resolve.ts]: I used that now 👍
