### PR TITLE
fix(cli): run terraform init in serial so no text file is busy in the cache

### LINKED ISSUE #2741: Error "text file busy" : Random conflict on parallel stack execution which use the same provider
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf = 0.15.5
Language = Python 3.10.10

### Affected Resource(s)

Any stack resource. 

### Debug Output

Context : We have 2 stack (testtac-elastic and testtac-redis) which will both use the HELM provider to install some chart, and both will be executed in parallel with the same `cdktf deploy testtac-elastic testtac-redis`. We have randomly this kind of issue which happen (1 time on 100).

``` 
testtac-elastic  Initializing the backend...
testtac-redis  Initializing the backend...
testtac-redis  
               Successfully configured the backend "azurerm"! Terraform will automatically
               use this backend unless the backend configuration changes.
testtac-redis  Initializing provider plugins...
               - Finding hashicorp/helm versions matching "2.9.0"...
testtac-redis  - Finding hashicorp/kubernetes versions matching "2.19.0"...
testtac-redis  - Installing hashicorp/helm v2.9.0...
testtac-redis  - Installed hashicorp/helm v2.9.0 (signed by HashiCorp)
testtac-redis  - Installing hashicorp/kubernetes v2.19.0...
testtac-redis  - Installed hashicorp/kubernetes v2.19.0 (signed by HashiCorp)

               Terraform has created a lock file .terraform.lock.hcl to record the provider
               selections it made above. Include this file in your version control repository
               so that Terraform can guarantee to make the same selections by default when
               you run "terraform init" in the future.
testtac-redis  Terraform has been successfully initialized!
               
               You may now begin working with Terraform. Try running "terraform plan" to see
               any changes that are required for your infrastructure. All Terraform commands
               should now work.

               If you ever set or change modules or backend configuration for Terraform,
               rerun this command to reinitialize your working directory. If you forget, other
               commands will detect it and remind you to do so if necessary.
testtac-redis  - Fetching hashicorp/kubernetes 2.19.0 for linux_amd64...
testtac-redis  - Retrieved hashicorp/kubernetes 2.19.0 for linux_amd64 (signed by HashiCorp)
testtac-redis  - Fetching hashicorp/helm 2.9.0 for linux_amd64...
testtac-redis  - Retrieved hashicorp/helm 2.9.0 for linux_amd64 (signed by HashiCorp)
               - Obtained hashicorp/helm checksums for linux_amd64; All checksums for this platform were already tracked in the lock file
               - Obtained hashicorp/kubernetes checksums for linux_amd64; All checksums for this platform were already tracked in the lock file
testtac-redis  Success! Terraform has validated the lock file and found no need for changes.
testtac-elastic  
                 Successfully configured the backend "azurerm"! Terraform will automatically
                 use this backend unless the backend configuration changes.
testtac-elastic  Initializing provider plugins...
                 - Finding hashicorp/helm versions matching "2.9.0"...
testtac-elastic  - Finding hashicorp/kubernetes versions matching "2.19.0"...
testtac-elastic  - Finding hashicorp/random versions matching "3.4.3"...
testtac-elastic  - Installing hashicorp/helm v2.9.0...
testtac-redis  ╷
               │ Error: Failed to load plugin schemas
               │ 
               │ Error while loading schemas for plugin components: Failed to obtain provider
               │ schema: Could not load the schema for provider
               │ registry.terraform.io/hashicorp/helm: failed to instantiate provider
               │ "registry.terraform.io/hashicorp/helm" to obtain schema: fork/exec
               │ .terraform/providers/registry.terraform.io/hashicorp/helm/2.9.0/linux_amd64/terraform-provider-helm_v2.9.0_x5:
               │ text file busy..
               ╵
/usr/lib/node_modules/cdktf-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Invoking Terraform CLI failed with exit code 1".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

### Expected Behavior

No fail during the execution, cdktf should prevent the situation where 2 stack completely independent in their behaviour but using the same provider impact each other.

### Actual Behavior

Random fail 1% of the time when 1 stack do it init step and the other one try to use it provider. We give this example but this happen in any other configuration where we have many stack execution in parallel which use the same provider

### Steps to Reproduce

Create 2 stack which use the same provider and run them in same time with `cdktf deploy stack1 stack2`

### References

This look like to be a common issue with terraform  parallel execution: 
- https://dev.to/mxglt/how-to-improve-terragrunt-pipeline--gk0
- https://github.com/uber/astro/issues/17

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
Closes #2741

### CODE REVIEW

File: packages/@cdktf/cli-core/src/lib/cdktf-project.ts [hunk 1]
```diff
@@ -559,4 +562,11 @@ export class CdktfProject {
       {}
     ) as NestedTerraformOutputs;
   }
+
+  // Serially run terraform init to prohibit text file busy errors for the cache files
+  private async initializeStacksToRunInSerial(): Promise<void> {
+    for (const stack of this.stacksToRun) {
+      await stack.initalizeTerraform();
```
Comment (ansgarm) [inline packages/@cdktf/cli-core/src/lib/cdktf-project.ts:569]: do we need to pass the `noColor` option here as well?

**Review by ansgarm — COMMENTED** [review]
Looks good! Is there a way we can test this?

**Comment by DanielMSchmidt** [comment]
Not that I'm aware of, the tests I could think of were too close to the code to be useful

**Review by ansgarm — APPROVED** [review]

**Review by ansgarm — APPROVED** [review]
