### PR TITLE
fix(lib): resolve objects correctly in cross stack references

### LINKED ISSUE #1481: Cross Stack References should support or error on passing entire objects
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When passing a [DomainValidationOptions](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acm_certificate#domain_validation_options) object across multiple stacks it's neither erroring, nor working. We should decide if we want to disallow this or support it.
The same is true for all objects:

- ComplexComputedLists
- ComplexComputedSets
- OutputReferences
- Resources (when passed to an output of another stack)

### References

- complex objects: https://github.com/hashicorp/terraform-cdk/pull/1416#issuecomment-1011143010
- resources: https://github.com/hashicorp/terraform-cdk/pull/1416#issuecomment-1011143851

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
Closes #1481

### CODE REVIEW

File: packages/cdktf/lib/tfExpression.ts [hunk 1]
```diff
@@ -194,6 +194,11 @@ function markAsInner(arg: any) {
   }
 }
 
+export function insideTfExpression(arg: any) {
```
Comment (ansgarm) [inline packages/cdktf/lib/tfExpression.ts:197]: nit: I'm a bit torn as I'm not quite happy with the name but don't know a better one 😅
Maybe add a docstring which describes something like "marks `arg` as being used in an inner Terraform expression and returns it for further use"?

File: packages/cdktf/test/resource.test.ts [hunk 2]
```diff
@@ -60,7 +60,13 @@ test("resource fqn", () => {
...
   });
 
-  expect(resource.fqn).toEqual("test_resource.test");
+  new TerraformOutput(stack, "result", {
+    value: resource.fqn,
+  });
+
+  expect(JSON.parse(Testing.synth(stack) as any).output.result.value).toEqual(
+    "${test_resource.test}"
+  );
```
Comment (ansgarm) [inline packages/cdktf/test/resource.test.ts:69]: I like how you adjusted this test 👍

**Review by ansgarm — APPROVED** [review]
