### PR TITLE
fix: detect destroys on windows / TF version

### LINKED ISSUE #2481: Windows: implicitly added var-file can be read by deploy but not by destroy
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

- Node on windows

### Expected Behavior

- Destroy should work

### Actual Behavior

- File open errors with the very same file

```
node  ╷
      │ Error: Failed to read variables file
      │
      │ Error while reading 'C:\Users\daniel\Desktop\cdktf\node\terraform.tfvars':
      │ open 'C:\Users\daniel\Desktop\cdktf\node\terraform.tfvars': The filename,
      │ directory name, or volume label syntax is incorrect..
      ╵


0 Stacks destroying     1 Stack done     0 Stacks waiting
Invoking Terraform CLI failed with exit code 1
PS C:\Users\daniel\Desktop\cdktf\node>
```

### Steps to Reproduce

- Create a cdktf project with a not-nullable var
- Add a `terraform.tfvars` file filling in that variable
- Run `cdktf deploy` -> Should work
- Run `cdktf destroy` -> Fails as it can not read the file

### References

- #0000

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
This PR also closes #2481

### CODE REVIEW

File: packages/@cdktf/cli-core/src/lib/models/deploy-machine.ts [hunk 1]
```diff
@@ -293,7 +301,9 @@ export function createAndStartDestroyService(options: {
   });
 
   options.varFiles?.forEach((v) => {
-    args.push(`-var-file='${v}'`);
+    args.push(
+      os.platform() === "win32" ? `-var-file=${v}` : `-var-file='${v}'`
+    );
```
Comment (ansgarm) [inline packages/@cdktf/cli-core/src/lib/models/deploy-machine.ts:306]: should we add this to deploy as well?

**Review by ansgarm — APPROVED** [review]

File: packages/@cdktf/cli-core/src/lib/models/deploy-machine.ts (hunk 1 above)
Comment (DanielMSchmidt) [reply packages/@cdktf/cli-core/src/lib/models/deploy-machine.ts:306]: lol, I never did the escaping in deploy so the bug was not there for this reason :D
