### PR TITLE
fix(cli): Wait for other stacks to complete if one of them failed

### LINKED ISSUE #1836: One stack failure when deploying multiple stack in parallel causes other stacks state to remain locked
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

$ cdktf --version
0.10.4

$ terraform --version
Terraform v1.2.1
on linux_amd64

Language: typescript

### Affected Resource(s)

Stack state files that did not fail but were running in parallel

### Expected Behavior
The stacks that did not fail should continue and complete. Once this is complete the error message for the stack that failed should be printed at the end. Also no other new stacks then should run. At the end of a failure the state file should not be locked for any of the stacks.

### Actual Behavior

Remote state file gets locked for the stacks that were running in parallel but did not fail

### Steps to Reproduce

1. Setup cdktf project with multiple stacks which can run in parallel
2. Make sure one of the stack fails while other stacks are not complete
3. Run the stacks in parallel
4. Look at the state file of the stacks that did not fail

### PR DESCRIPTION
**Pull request by ansgarm**
- chore: replicate deployment bug
- fix(cli): fix test as planning steps have no ensured order
- fix(cli): Wait for other work promises to complete even if one of them failed, which causes .race and .all to short circuit

Closes #1836

### CODE REVIEW

File: packages/cdktf-cli/lib/cdktf-project.ts [hunk 1]
```diff
@@ -527,24 +534,49 @@ export class CdktfProject {
...
+            ? nextRunningExecutor.deploy(refreshOnly)
+            : nextRunningExecutor.destroy();
+        } catch (e) {
+          // await next() threw an error because a stack failed to apply/destroy
+          // wait for all other currently running stacks to complete before propagating that error
+          logger.debug(
+            "Encountered an error while awaiting stack to finish",
+            e
+          );
+          logger.debug("Waiting for still running stacks to finish");
```
Comment (DanielMSchmidt) [inline packages/cdktf-cli/lib/cdktf-project.ts:553]: Nit: Maybe we can add the currently open stacks here for a better debugging log line

File: packages/cdktf-cli/lib/cdktf-project.ts [hunk 2]
```diff
@@ -527,24 +534,49 @@ export class CdktfProject {
...
     }
 
     // We end the loop when all stacks are started, now we need to wait for them to be done
-    await Promise.all(
-      this.stacksToRun
-        .filter((ex) => ex.currentWorkPromise)
-        .map((ex) => ex.currentWorkPromise)
-    );
+    // We wait for all work to finish even if one of the promises threw an error.
+    const currentWork = this.stacksToRun
```
Comment (DanielMSchmidt) [inline packages/cdktf-cli/lib/cdktf-project.ts:569]: I wonder if we can make this part a method, seems like we have a core function to execute and wait for all promises to settle in the event of an error

File: packages/cdktf-cli/test/lib/cdktf-project.test.ts [hunk 3]
```diff
@@ -350,6 +368,66 @@ describe("CdktfProject", () => {
...
+        throw new Error("This error should not be thrown");
+      } catch (e) {
+        expect(e).toMatchInlineSnapshot(`[Error: non-zero exit code 1]`);
+      }
+
+      const relevantEvents = events
+        .filter((e) => !e.type.includes("update"))
+        .map((e) => `${e.stackName || "global"}: ${e.type}`);
+
+      // the first 5 events have a stable order
```
Comment (DanielMSchmidt) [inline packages/cdktf-cli/test/lib/cdktf-project.test.ts:399]: Do we even need these?

**Review by DanielMSchmidt — APPROVED** [review]

File: packages/cdktf-cli/test/lib/cdktf-project.test.ts (hunk 3 above)
Comment (ansgarm) [reply packages/cdktf-cli/test/lib/cdktf-project.test.ts:399]: I think it still makes sense to test that these events correctly occur. This helps spotting issues that cause the test to fail, that might not be directly related to the other events which we test. E.g. if one of those first five events was missing, the other assertions would fail and it would be hard to spot why everything shifted in the array by one element (due to the missing event that is never mentioned in the test).

File: packages/cdktf-cli/lib/cdktf-project.ts (hunk 1 above)
Comment (ansgarm) [reply packages/cdktf-cli/lib/cdktf-project.ts]: done

File: packages/cdktf-cli/test/lib/cdktf-project.test.ts (hunk 3 above)
Comment (DanielMSchmidt) [reply packages/cdktf-cli/test/lib/cdktf-project.test.ts:399]: Fair point 👍
