### PR TITLE
fix(cli): reflect correct node version requirement

### LINKED ISSUE #1538: SyntaxError Unexpected Token ? following install
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
I installed cdktf-cli using `sudo npm install --global cdktf-cli@next`. I ran help as part of the tutorial https://learn.hashicorp.com/tutorials/terraform/cdktf-install
It errored out.

### Debug Output
https://gist.github.com/blade2005/c6569e956880cdf5f62c165345557b42

### Expected Behavior
Help to be shown.

### Actual Behavior
SyntaxError

### Steps to Reproduce
1. WSL2 Debian
2. install npm from apt
3. install using `sudo npm install --global cdktf-cli@next`
4. `cdktf --help`

### References

- #0000

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
Fixes #1538

### CODE REVIEW

**Review by ansgarm — APPROVED** [review]

File: packages/cdktf-cli/bin/cmds/helper/check-environment.ts [hunk 1]
```diff
@@ -52,7 +52,7 @@ async function checkGoVersion(command: string) {
 
 async function checkNodeVersion(command: string) {
   const out = await getBinaryVersion(command, "node", "--version");
-  throwIfLowerVersion(command, "Node.js", "12.16.0", out);
+  throwIfLowerVersion(command, "Node.js", "14.0.0", out);
```
Comment (ansgarm) [inline packages/cdktf-cli/bin/cmds/helper/check-environment.ts:55]: there are also other files that need to be updated 🙈 see https://github.com/hashicorp/terraform-cdk/pull/1572#pullrequestreview-884412534

Comment (DanielMSchmidt) [reply packages/cdktf-cli/bin/cmds/helper/check-environment.ts:55]: done 👍
