### PR TITLE
fix(provider-generator): use terraform get instead of init to download modules

### LINKED ISSUE #2026: Error running `cdktf get` with community module requiring parent provider metadata
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

```
cdktf debug
language: typescript
cdktf-cli: 0.12.0
node: v16.16.0
cdktf: 0.12.0
constructs: 10.1.75
jsii: null
terraform: 1.2.7
arch: x64
os: darwin 20.6.0
```

### Affected Resource(s)

Can't use higher level module: `milliHQ/next-js/aws@1.0.0-canary.5`

### Debug Output

The output for 
```sh
% CDKTF_LOG_LEVEL=debug cdktf get
```
https://gist.github.com/qcho/9f2a3e94259a2af55534d2547b136656

### Expected Behavior

When running `cdktf get`, CDK Constructs for Terraform providers and modules should be generated so i can start coding my `main.ts` file.

### Actual Behavior

Error is shown. No `.gen/` folder gets generated.

```sh
% cdktf get
⠋ downloading and generating modules and providers...
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│ Error: Missing required provider configuration
│
│   on main.tf.json line 1, in module:
│    1: {"terraform":{},"module":{"milliHQ_next-js_aws":{"source":"milliHQ/next-js/aws","version":"1.0.0-canary.5"}}}
│
│ The child module requires an additional configuration for provider
│ hashicorp/aws, with the local name "aws.global_region".
│
│ Refer to the module's documentation to understand the intended purpose of
│ this additional provider configuration, and then add an entry for
│ aws.global_region in the "providers" meta-argument in the module block to
│ choose which provider configuration the module should use for that purpose.
╵
Error: non-zero exit code 1
    at ChildProcess.<anonymous> (/Users/qcho/.nvm/versions/node/v16.16.0/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:46:2065)
    at Object.onceWrapper (node:events:642:26)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess.emit (node:domain:475:12)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  stderr: '\x1B[31m\x1B[0mThere are some problems with the configuration, described below.\n' + ...
}
⠙ downloading and generating modules and providers...
non-zero exit code 1
```

### Steps to Reproduce

Just create a new project
```sh
% mkdir reproduce
% cdktf init --local --template typescript
```
Add `milliHQ/next-js/aws` module to `cdktf.json`:
```json
  "terraformModules": [
    "milliHQ/next-js/aws@1.0.0-canary.5"
  ],
  ```
Execute `cdktf get`

#### Things I tried that didn't work
* Adding `aws@~>4.0` to `terraformProviders`.
* Adding aws@~>4.0` to `terraformProviders` with name `aws.global_region`.
* Seems unrelated but tried to edit `main.ts` file by:
  * Adding `AwsProvider` with alias `global_region`.
  * Replace it with output from `cdktf convert` on `main.tf` from the referenced registry doc.
### Important Factoids

No

### References

You can find an example `main.tf` file for the related module here: https://registry.terraform.io/modules/milliHQ/next-js/aws/1.0.0-canary.5

It seems there is a problem with the reference of expected aliased providers that are not being declared anywhere yet.

- #0000

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
Fixes #2026

### CODE REVIEW

File: packages/@cdktf/provider-generator/lib/index.ts [hunk 1]
```diff
@@ -79,5 +79,7 @@ export async function readSchema(
     moduleSchema: {},
   });
 
-  return deepmerge.all(schemas);
+  const x = deepmerge.all(schemas);
+  console.log(x);
```
Comment (ansgarm) [inline packages/@cdktf/provider-generator/lib/index.ts:83]: leftover?

**Review by ansgarm — APPROVED** [review]

File: packages/@cdktf/provider-generator/lib/index.ts (hunk 1 above)
Comment (DanielMSchmidt) [reply packages/@cdktf/provider-generator/lib/index.ts]: yeah :D
