### PR TITLE
fix(lib): Delay complex object fqn so that override id can still be used

### LINKED ISSUE #1656: CDKTF dependsOn broken when using overrideLogicalId
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf@0.9.4

### Affected Resource(s)

All.

### Expected Behavior

Resources using `overrideLogicalId()` should function when referenced by other resources.

### Actual Behavior

Resources using  `overrideLogicalId()` update the TF resource name to the new name but no longer properly handle references to them. This causes TF plan/apply failures shown below (`sqs-lambda-drop_dlq` is the TF resource name after using `overrideLogicalId()`, depends_on is attempting to reference `sqs-lambda-drop_dlq_EF847697` (the original name before override))

│ Error: Reference to undeclared resource
│ 
│   on redacted.tf.json line 452, in resource.aws_sqs_queue.sqs-lambda-drop_queue.depends_on:
│  452:           "aws_sqs_queue.sqs-lambda-drop_dlq_EF847697"
│ 
│ A managed resource "aws_sqs_queue" "sqs-lambda-drop_dlq_EF847697" has not
│ been declared in the root module.
╵

### Steps to Reproduce

1. Create a TF resource.
2. Override the logical name using overrideLogicalId()
3. Create a second TF resource and have it explicitly depend on the first (TF depends_on)
4. Run terraform plan

### Important Factoids

This may have regressed in https://github.com/hashicorp/terraform-cdk/commit/88f852bd82a7bb9391302ffbac6eb026f2b3bfbb .  The commit changes the FQN to be calculated in the constructor instead of lazily when requested which appears to be used by other resources when creating their depends on list.

### References

- https://github.com/hashicorp/terraform-cdk/commit/88f852bd82a7bb9391302ffbac6eb026f2b3bfbb

### PR DESCRIPTION
**Pull request by jsteinich**
Closes #1656

#1779 introduced changes to fix #1656; however, #1725 made those fixes no longer work in all cases. This fixes that by applying a similar technique as the original fix.

### CODE REVIEW

File: packages/cdktf/lib/complex-computed-list.ts [hunk 1]
```diff
@@ -17,11 +21,19 @@ abstract class ComplexResolvable implements IResolvable, ITerraformAddressable {
     this.creationStack = captureStackTrace();
   }
 
-  abstract fqn: string;
+  abstract computeFqn(): string;
+
+  get fqn(): string {
+    if (!this._fqn) {
+      this._fqn = this.computeFqn();
```
Comment (DanielMSchmidt) [inline packages/cdktf/lib/complex-computed-list.ts:28]: Wouldn't this be a great place to use a lazy token instead?

**Review by DanielMSchmidt — APPROVED** [review]
Looks good in general :)

File: packages/cdktf/lib/complex-computed-list.ts (hunk 1 above)
Comment (jsteinich) [reply packages/cdktf/lib/complex-computed-list.ts:28]: No. Lazy results in failed cross stack references due to how / when it is being resolved.
