### PR TITLE
fix(cli): handle missing package versions for non-npm packages

### LINKED ISSUE #2065: pre-built provider azurerm: trying to add provider for azurerm to go app returns error of invalid version
Running `cdktf provider add "azurerm"`

```
C:\g\tfcdk\aci> cdktf provider add "azurerm"
Checking whether pre-built provider exists for the following constraints:
  provider: azurerm
  version : latest
  language: go
  cdktf   : 0.12.1

Found pre-built provider.
Adding package github.com/hashicorp/cdktf-provider-azurerm-go/azurerm @ 2.0.10
[2022-08-19T11:26:27.556] [ERROR] default - go get: github.com/hashicorp/cdktf-provider-azurerm-go/azurerm/v2@v2.0.10: invalid version: unknown revision azurerm/v2.0.10

go get: github.com/hashicorp/cdktf-provider-azurerm-go/azurerm/v2@v2.0.10: invalid version: unknown revision azurerm/v2.0.10
Error: non-zero exit code 1
    at ChildProcess.<anonymous> (C:\Users\auser\AppData\Roaming\npm\node_modules\cdktf-cli\bundle\bin\cmds\handlers.js:433:933)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at e.emit (C:\Users\auser\AppData\Roaming\npm\node_modules\cdktf-cli\bundle\bin\cmds\handlers.js:139:20414)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
Collecting Debug Information...
C:\Users\auser\AppData\Roaming\npm\node_modules\cdktf-cli\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

Error: non-zero exit code 1
    at ChildProcess.<anonymous> (C:\Users\auser\AppData\Roaming\npm\node_modules\cdktf-cli\bundle\bin\cmds\handlers.js:433:933)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at e.emit (C:\Users\auser\AppData\Roaming\npm\node_modules\cdktf-cli\bundle\bin\cmds\handlers.js:139:20414)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  stderr: 'go get: github.com/hashicorp/cdktf-provider-azurerm-go/azurerm/v2@v2.0.10: invalid version: unknown revision azurerm/v2.0.10\n'
}

```

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
The previous implementation assumes that for every released npm version
there is an matching release on the other package managers. This sometimes
is not true, mostly by errors in the publishing process. To hide this and make
the UX of provider add nicer we will deploy the latest compatible matching version.

Closes #2065

### CODE REVIEW

File: packages/cdktf-cli/lib/dependencies/prebuilt-providers.ts [hunk 1]
```diff
@@ -207,7 +207,7 @@ function cdktfVersionMatches(
 export async function getPrebuiltProviderVersion(
```
Comment (ansgarm) [inline packages/cdktf-cli/lib/dependencies/prebuilt-providers.ts:207]: Let's rename this
```suggestion
export async function getPrebuiltProviderVersions(
```

File: packages/cdktf-cli/lib/dependencies/prebuilt-providers.ts [hunk 2]
```diff
@@ -228,9 +228,11 @@ export async function getPrebuiltProviderVersion(
...
-  if (matchingVersion) {
-    return matchingVersion.packageVersion;
+  if (!matchingVersions.length) {
+    return null;
   }
-
-  return null;
+  const npmPackageVersions = matchingVersions
+    .map((matchingVersion) => matchingVersion.packageVersion)
+    .sort(semver.compare);
```
Comment (ansgarm) [inline packages/cdktf-cli/lib/dependencies/prebuilt-providers.ts:236]: nice!

File: packages/cdktf-cli/lib/dependencies/package-manager.ts [hunk 3]
```diff
@@ -173,6 +213,39 @@ class NugetPackageManager extends PackageManager {
...
+    const id = parts.slice(1).join(".");
+    const url = `https://azuresearch-usnc.nuget.org/query?q=owner:${owner}%20id:${id}&prerelease=false&semVerLevel=2.0.0`;
+    logger.debug(`Fetching package metadata from Nuget: '${url}'`);
+
+    const response = await fetch(url);
+    const json = (await response.json()) as {
+      data: { id: string; versions: { version: string }[] }[];
+    };
+    logger.debug(
+      `Got response from Nuget for ${packageName} : ${JSON.stringify(json)}`
```
Comment (ansgarm) [inline packages/cdktf-cli/lib/dependencies/package-manager.ts:234]:
```suggestion
      `Got response from NuGet for ${packageName} : ${JSON.stringify(json)}`
```

File: packages/cdktf-cli/lib/dependencies/package-manager.ts [hunk 4]
```diff
@@ -217,6 +290,38 @@ class MavenPackageManager extends PackageManager {
...
+        `Expected package name to be in format "group.artifact", e.g. "com.hashicorp.cdktf-provider-google", got: ${packageName}`
+      );
+    }
+
+    const packageIdentifier = parts.pop();
+    const groupId = parts.join(".");
+
+    const url = `https://search.maven.org/solrsearch/select?q=g:${groupId}+AND+a:${packageIdentifier}+AND+v:${packageVersion}&rows=5&wt=json`;
+    logger.debug(
+      `Trying to find package version by querying maven central under '${url}'`
```
Comment (ansgarm) [inline packages/cdktf-cli/lib/dependencies/package-manager.ts:312]:
```suggestion
      `Trying to find package version by querying Maven Central under '${url}'`
```

File: packages/cdktf-cli/lib/dependencies/package-manager.ts [hunk 5]
```diff
@@ -217,6 +290,38 @@ class MavenPackageManager extends PackageManager {
...
+    );
+    const response = await fetch(url);
+
+    const json = await response.json();
+    logger.debug(
+      `Got response from the maven package search for ${packageName}: ${JSON.stringify(
```
Comment (ansgarm) [inline packages/cdktf-cli/lib/dependencies/package-manager.ts:318]:
```suggestion
      `Got response from the Maven package search for ${packageName}: ${JSON.stringify(
```

File: packages/cdktf-cli/test/lib/dependencies/prebuilt-providers.test.ts [hunk 6]
```diff
@@ -184,7 +184,7 @@ describe("prebuilt-providers", () => {
         .replyWithError({ code: "ETIMEDOUT" });
 
       await expect(
-        getPrebuiltProviderVersion(
+        getPrebuiltProviderVersions(
```
Comment (ansgarm) [inline packages/cdktf-cli/test/lib/dependencies/prebuilt-providers.test.ts:187]: Do these tests need an update? The function returns an array now, doesn't it?

Comment (ansgarm) [reply packages/cdktf-cli/test/lib/dependencies/prebuilt-providers.test.ts:187]: They might also need new test cases / adjusted mocks for the newly added requests?

**Review by ansgarm — COMMENTED** [review]
Nice work! Just some nits and the tests might need updates/fixes.

File: packages/cdktf-cli/lib/dependencies/package-manager.ts [hunk 7]
```diff
@@ -76,6 +83,14 @@ class NodePackageManager extends PackageManager {
 
     console.log("Package installed.");
   }
+
+  public async isVersionAvailable(
+    _packageName: string,
+    _packageVersion: string
+  ): Promise<boolean> {
+    // We get the list of available versions from npm, no need to check here
+    return true;
```
[the remark this answers is not in the document]
Comment (ansgarm) [reply packages/cdktf-cli/lib/dependencies/package-manager.ts:92]: 👍

**Review by ansgarm — APPROVED** [review]
🚀
