### PR TITLE
Drop custom symlink for generic plugin cache setting

### LINKED ISSUE #189: Moving / Renaming a Project Leads to Symlink Error
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

All

### Debug Output

```
⠙ synthesizing ...
internal/fs/utils.js:230
    throw err;
    ^

Error: EEXIST: file already exists, symlink '/Users/sebastian/projects/cdk/terraform-cdk/examples/typescript-google/.terraform' -> '/Users/sebastian/projects/cdk/terraform-cdk/examples/typescript-google/cdktf.out/.terraform'
    at Object.symlinkSync (fs.js:1108:3)
    at MyStack.linkDotTerraform (/Users/sebastian/projects/cdk/terraform-cdk/packages/cdktf/lib/terraform-stack.js:98:16)
    at MyStack.onSynthesize (/Users/sebastian/projects/cdk/terraform-cdk/packages/cdktf/lib/terraform-stack.js:91:14)
    at Node.synthesize (/Users/sebastian/projects/cdk/terraform-cdk/node_modules/constructs/lib/construct.js:342:27)
    at App.synth (/Users/sebastian/projects/cdk/terraform-cdk/packages/cdktf/lib/app.js:32:36)
    at Object.<anonymous> (/Users/sebastian/projects/cdk/terraform-cdk/examples/typescript-google/main.js:37:5)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14) {
  errno: -17,
  syscall: 'symlink',
  code: 'EEXIST',
  path: '/Users/sebastian/projects/cdk/terraform-cdk/examples/typescript-google/.terraform',
  dest: '/Users/sebastian/projects/cdk/terraform-cdk/examples/typescript-google/cdktf.out/.terraform'
}
non-zero exit code 1
```

### Expected Behavior

When moving a project which has been used already (and therefore has  a `cdktf.out` folder) should continue to be usable when moving / renaming the project folder.

### Actual Behavior

All `cdktf` deploy / diff / synth / destroy commands will fail and complain about the existing symlink.

### Steps to Reproduce

Rename a project folder

### LINKED ISSUE #222: Windows: cdktf deploy - symlink not permitted
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf version : `0.0.12-pre.4c00f2bafb17b79dcf2310a2a85a4ef9ed6518a1`
TypeScript

### Affected Resource(s)

All, Docker example

### Debug Output

```
❯ cdktf deploy
⠸ synthesizing ...
internal/fs/utils.js:298
    throw err;
    ^

Error: EPERM: operation not permitted, symlink 'C:\Dev\satak\terraform-vm-test\.terraform' -> 'C:\Dev\satak\terraform-vm-test\cdktf.out\.terraform'
    at Object.symlinkSync (fs.js:1121:3)
    at MyStack.linkDotTerraform (C:\Dev\satak\terraform-vm-test\node_modules\cdktf\lib\terraform-stack.js:98:16)
    at MyStack.onSynthesize (C:\Dev\satak\terraform-vm-test\node_modules\cdktf\lib\terraform-stack.js:91:14)
    at Node.synthesize (C:\Dev\satak\terraform-vm-test\node_modules\constructs\lib\construct.js:342:27)
    at App.synth (C:\Dev\satak\terraform-vm-test\node_modules\cdktf\lib\app.js:32:36)
    at Object.<anonymous> (C:\Dev\satak\terraform-vm-test\main.js:26:5)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14) {
  errno: -4048,
  syscall: 'symlink',
  code: 'EPERM',
  path: 'C:\\Dev\\satak\\terraform-vm-test\\.terraform',
  dest: 'C:\\Dev\\satak\\terraform-vm-test\\cdktf.out\\.terraform'
⠼ synthesizing ...
```

### Expected Behavior

deploy should work without elevated (terminal opened as admin) rights

### Actual Behavior

Deploy fails on permissions while trying to create symlink

### Steps to Reproduce

Try to deploy Docker example with TypeScript on VS Code terminal (pwsh 7.0) from terminal that is not opened as admin

### Other

I can't open my terminal as admin since it's not company policy to have terminals opened as admin. Make a workaround to copy files without symlink, like:

```js
try {
  fs.symlinkSync(absoluteFilePath, outputFilePath);
} catch(e) {
  const conentStr = fs.readFileSync(absoluteFilePath);
  fs.writeFileSync(outputFilePath, conentStr);
}
```

### LINKED ISSUE #349: Optional terraform binaries
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Our setup:
- We work with `typescript` template
- We use Azure
- We use ts-node to run the code w/o compiling to a files
- We use generated terraform json to run in Azure DevOps release pipelines

Would be great to have an option not to make symbolic link to `.terraform` when doing synth

### PR DESCRIPTION
**Pull request by skorfmann**
Since the current symlink approach for caching poviders has multiple
drawbacks, this PR switches to the general plugin cache dir supported
by Terraform directly.

https://www.terraform.io/docs/commands/cli-config.html#provider-plugin-cache

Fixes #189
Fixes #222
Fixes #349

### CODE REVIEW

**Comment by skorfmann** [comment]
Looks like lots of parallel provider downloads and `TF_PLUGIN_CACHE_DIR` aren't working well together - I know I had similar issues with Terragrunt in another project.

Perhaps we could think about adding all used providers to the Docker image in advance - Or have one bootstrap step where all used providers are fetched sequentially.

**Comment by skorfmann** [comment]
Again, it'd be pretty helpful to have the Docker image published automatically (#36) /cc @anubhavmishra

File: tools/bootstrap-plugin-cache.sh [hunk 1]
```diff
@@ -0,0 +1,21 @@
+#!/bin/sh
+set -euo pipefail
+
+# Disable spinner even when we have a TTY
+export CI='1'
+
+find ./examples -type f -name '*cdktf.json' |  tr '\n' " " | xargs jq -s "map(.terraformProviders) | add | unique | { \"language\": \"typescript\", \"terraformProviders\": . }" > bootstrap.json
```
Comment (skorfmann) [inline tools/bootstrap-plugin-cache.sh:7]: I don't think there's an easy way to represent this on Windows. If it wasn't for this line, I think we could easily convert it to a JS file and make it platform independent. What do you think @jsteinich ?

Comment (skorfmann) [reply tools/bootstrap-plugin-cache.sh:7]: But yeah, doing this in JS as well shouldn't be an issue

Comment (jsteinich) [reply tools/bootstrap-plugin-cache.sh:7]: I'm certainly not aware of any reasonable one-liner in Windows for doing that.

Doesn't seem like it would be too difficult to convert that to JS, though I'm not certain when we'll run this on Windows.

Out of curiosity, does that last pipe (before file) append that block to the output? I don't recall seeing anything like that before.

File: tools/bootstrap-plugin-cache.sh [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+
+scriptdir=$(cd $(dirname $0) && pwd)
+
+cd $(mktemp -d)
+mkdir test && cd test
+
+cdktf init --template typescript-minimal --project-name="typescript-bootstrap" --project-description="typescript bootstrap plugin cache" --local
+
+# add null provider
+mv ${scriptdir}/../bootstrap.json ./cdktf.json
```
Comment (jsteinich) [inline tools/bootstrap-plugin-cache.sh:17]: As we expand what's in `cdktf.json`, I could see this overwriting some useful information.

File: tools/bootstrap-plugin-cache.sh (hunk 1 above)
Comment (skorfmann) [reply tools/bootstrap-plugin-cache.sh:7]: > Out of curiosity, does that last pipe (before file) append that block to the output? I don't recall seeing anything like that before.

Not sure which part you mean

File: tools/bootstrap-plugin-cache.sh (hunk 2 above)
Comment (skorfmann) [reply tools/bootstrap-plugin-cache.sh:17]: It's only about downloading the providers to warm up the cache. I don't think there will be any custom logic involved.

File: tools/bootstrap-plugin-cache.sh (hunk 1 above)
Comment (jsteinich) [reply tools/bootstrap-plugin-cache.sh:7]: `| { \"language\": \"typescript\", \"terraformProviders\": . }`

Comment (skorfmann) [reply tools/bootstrap-plugin-cache.sh:7]: Oh, that's [jq](https://stedolan.github.io/jq/) syntax, where the a new JSON object is constructed and the `.` represents the piped content - which happens to be a list of provider strings at that point.

Comment (skorfmann) [reply tools/bootstrap-plugin-cache.sh:7]: I think this would certainly benefit from not being an obscure one-liner, but more readable Javascript code. Gonna change that.

Comment (jsteinich) [reply tools/bootstrap-plugin-cache.sh:7]: Ah, I missed that it was still within the quotes.

File: packages/cdktf-cli/bin/cdktf.ts [hunk 3]
```diff
@@ -2,6 +2,21 @@ process.env.NODE_ENV = process.env.NODE_ENV || 'production'
...
+
+const ensurePluginCache = (): string => {
+  const pluginCachePath = process.env.TF_PLUGIN_CACHE_DIR || path.join(os.homedir(), '.terraform.d', 'plugin-cache')
+  if (!fs.existsSync(pluginCachePath)) {
+    fs.mkdirpSync(pluginCachePath)
+  }
+  return pluginCachePath;
+}
+
+if (!process.env.DISABLE_PLUGIN_CACHE_ENV) {
```
Comment (anubhavmishra) [inline packages/cdktf-cli/bin/cdktf.ts:17]:
```suggestion
if (!process.env.CDKTF_DISABLE_PLUGIN_CACHE_ENV) {
```

File: packages/cdktf-cli/bin/cdktf.ts [hunk 4]
```diff
@@ -15,6 +30,7 @@ const args = yargs
   .help()
   .alias('h', 'help')
   .option('disable-logging', { type: 'boolean', default: true, required: false, desc: 'Dont write log files. Supported using the env CDKTF_DISABLE_LOGGING.'})
+  .option('disable-plugin-cache-env', { type: 'boolean', default: false, required: false, desc: 'Dont set TF_PLUGIN_CACHE_DIR automatically. This is useful when the plugin cache is configured differently. Supported using the env DISABLE_PLUGIN_CACHE_ENV.'})
```
Comment (anubhavmishra) [inline packages/cdktf-cli/bin/cdktf.ts:33]:
```suggestion
  .option('disable-plugin-cache-env', { type: 'boolean', default: false, required: false, desc: 'Dont set TF_PLUGIN_CACHE_DIR automatically. This is useful when the plugin cache is configured differently. Supported using the env CDKTF_DISABLE_PLUGIN_CACHE_ENV.'})
```

**Comment by skorfmann** [comment]
> We can add a note in the docs to show that we are setting the `TF_PLUGIN_CACHE_DIR` environment variable.

Done
