### PR TITLE
fix(provider-generator): don't require attributes to be set on nested_type

### LINKED ISSUE #3144: Error: unknown type {"nesting_mode":"single"}
### Expected Behavior

Running [CDKTF Getting Started](https://developer.hashicorp.com/terraform/tutorials/cdktf/cdktf-install) but instead replacing the docker provider with the `pingidentity/pingone` provider, expecting project to initialise successfully.

### Actual Behavior

Error returned:

```
[2023-09-25T09:57:54.000] [INFO] default - Adding local provider registry.terraform.io/pingidentity/pingone with version constraint undefined to cdktf.json
Local providers have been updated. Running cdktf get to update...
Error: unknown type {"nesting_mode":"single"}
    at w$.renderAttributeType (/usr/local/Cellar/cdktf/0.18.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:94:70757)
    at w$.renderAttributesForBlock (/usr/local/Cellar/cdktf/0.18.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:94:71060)
    at w$.resourceFrom (/usr/local/Cellar/cdktf/0.18.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:94:68376)
    at iS.parse (/usr/local/Cellar/cdktf/0.18.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:94:74117)
    at /usr/local/Cellar/cdktf/0.18.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:95:12793
    at Array.map (<anonymous>)
    at aS.buildResourceModels (/usr/local/Cellar/cdktf/0.18.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:95:12760)
    at aS.emitProvider (/usr/local/Cellar/cdktf/0.18.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:95:13308)
    at aS.generate (/usr/local/Cellar/cdktf/0.18.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:95:12338)
    at X$.generateTypescriptProvider (/usr/local/Cellar/cdktf/0.18.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:101:17429)
⠏ downloading and generating modules and providers...
Error: unknown type {"nesting_mode":"single"}
```

### Steps to Reproduce

1. `cdktf init --template=java --providers=pingidentity/pingone --local`

### Versions

language: java
cdktf-cli: 0.18.0
node: v20.6.1
cdktf: 0.18.0
constructs: 10.0.25
jsii: null
terraform: 1.5.7
arch: x64
os: darwin 22.6.0
java: 
maven: null
gradle: ------------------------------------------------------------Gradle 8.3------------------------------------------------------------Build time:   2023-08-17 07:06:47 UTCRevision:     8afbf24b469158b714b36e84c6f4d4976c86fcd5Kotlin:       1.9.0Groovy:       3.0.17Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023JVM:          20.0.2.1 (Amazon.com Inc. 20.0.2.1+10-FR)OS:           Mac OS X 13.5.2 x86_64

### Providers

┌──────────────────────┬──────────────────┬───────┬────────────┬──────────────┬─────────────────┐
│ Provider Name        │ Provider Version │ CDKTF │ Constraint │ Package Name │ Package Version │
├──────────────────────┼──────────────────┼───────┼────────────┼──────────────┼─────────────────┤
│ pingidentity/pingone │                  │       │ ~> 0.21    │              │                 │
└──────────────────────┴──────────────────┴───────┴────────────┴──────────────┴─────────────────┘

### Gist

_No response_

### Possible Solutions

_No response_

### Workarounds

_No response_

### Anything Else?

- Provider muxes v5 and v6 TF protocol resources/data sources

### References

_No response_

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by Maed223**
### Related issue

Fixes #3144

### Description

Don't require `nested_type` to have `attributes` defined.  Relevant for certain use cases where just the presence of an attribute is used to define the resource. 

Such as...
```json
"predictor_bot_detection": {
                "nested_type": {
                  "nesting_mode": "single"
                },
                "description": "A single nested object that specifies options for the Bot Detection predictor.  At least one of the following must be defined: `predictor_anonymous_network`, `predictor_bot_detection`, `predictor_composite`, `predictor_custom_map`, `predictor_device`, `predictor_geovelocity`, `predictor_ip_reputation`, `predictor_user_location_anomaly`, `predictor_user_risk_behavior`, `predictor_velocity`.",
                "description_kind": "markdown",
                "optional": true
              },
```
 Where just the presence of predictor_bot_detection = {} in  HCL is enough to define the predictor type.

### Example

```typescript
// Copyright (c) HashiCorp, Inc
// SPDX-License-Identifier: MPL-2.0
import { Construct } from "constructs";
import { App, TerraformStack } from "cdktf";
import { RiskPredictor } from "./.gen/providers/pingone/risk-predictor";
import { PingoneProvider } from "./.gen/providers/pingone/provider";

class MyStack extends TerraformStack {
  constructor(scope: Construct, id: string) {
    super(scope, id);

    new PingoneProvider(this, "provider", {});

    new RiskPredictor(this, "risk-predictor", {
      compactName: "name",
      name: "name",
      environmentId: "832794",
      predictorBotDetection: {},
    });
  }
}

const app = new App();
new MyStack(app, "my-example");
app.synth();
```

#### cdk.tf.json

```json
{
  "//": {
    "metadata": {
      "backend": "local",
      "stackName": "my-example",
      "version": "0.0.0"
    },
    "outputs": {
    }
  },
  "provider": {
    "pingone": [
      {
      }
    ]
  },
  "resource": {
    "pingone_risk_predictor": {
      "risk-predictor": {
        "//": {
          "metadata": {
            "path": "my-example/risk-predictor",
            "uniqueId": "risk-predictor"
          }
        },
        "compact_name": "name",
        "environment_id": "832794",
        "name": "name",
        "predictor_bot_detection": {
        }
      }
    }
  },
  "terraform": {
    "backend": {
      "local": {
        "path": "/Users/mark.decrane/terraform-cdk/examples/typescript/ping-identity/terraform.my-example.tfstate"
      }
    },
    "required_providers": {
      "pingone": {
        "source": "pingidentity/pingone",
        "version": "0.23.1"
      }
    }
  }
}
```

### Checklist

- [ ] I have updated the PR title to match [CDKTF's style guide](https://github.com/hashicorp/terraform-cdk/blob/main/CONTRIBUTING.md#pull-requests-1)
- [ ] I have run the linter on my code locally
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation if applicable
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works if applicable
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: packages/@cdktf/provider-generator/lib/get/generator/resource-parser.ts [hunk 1]
```diff
@@ -569,52 +569,54 @@ class Parser {
...
-          optional: optional,
-          terraformName,
-          terraformFullName: parent.fullName(terraformName),
-          type,
-          provider: parent.isProvider,
-          required: required,
-        })
-      );
+    if (attrs) {
+      for (const [terraformName, att] of Object.entries(attrs)) {
```
Comment (DanielMSchmidt) [inline packages/@cdktf/provider-generator/lib/get/generator/resource-parser.ts:578]: Or remove the if and do

```suggestion
      for (const [terraformName, att] of Object.entries(attrs || {})) {
```

**Review by DanielMSchmidt — APPROVED** [review]
